function g = growthterms_c2_withgrowthfactors(c1,c2,q1,q2,PO2,Pm,alpha21,...
    alpha22,beta1,beta2,beta3,gamma2,cmax,hyaloid)
% g = growthterms_c2_withgrowthfactors(c1,c2,q1,q2,PO2,Pm,alpha21,...
%     alpha22,beta1,beta2,beta3,gamma2,cmax,hyaloid)
%
% growth terms just IPAs (c2): g2

hyaloid = hyaloid(1:length(c1));
choroid = PO2./(Pm+PO2);

g = ( alpha21*(hyaloid + choroid) + alpha22*q1 ).*c2.*(1 - (c1+c2)/cmax) ...
    + (beta1/cmax)*c1.*c2 ...
    + ( beta2*(hyaloid + choroid) + beta3*q2 ).*c1 ...
    - gamma2.*c2;