function [params,errors] = par_load18(fname)

load(fname,'mu','alpha10','alpha11','alpha12','alpha13','alpha20',...
    'alpha21','alpha22','alpha23','beta0','beta1','beta2','beta3',...
    'beta4','eta1','eta2','P_hy','r_hy','err_tot','err_time','err_rad',...
    'err_dens','err_flag')
params = [mu,alpha10,alpha11,alpha12,alpha13,alpha20,alpha21,...
    alpha22,alpha23,beta0,beta1,beta2,beta3,beta4,eta1,eta2,P_hy,r_hy];
errors = {err_tot,err_time,err_rad,err_dens,err_flag};

end